name: "Build"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-23.05
    - uses: cachix/cachix-action@v12
      with:
        name: vaibhavsagar
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build
    - run: ./.github/workflows/update_pages.sh
      env:
        GITHUB_TOKEN: ${{ secrets.BLOG_GITHUB_TOKEN }}
        TARGET_REPO: 'vaibhavsagar/vaibhavsagar.github.io'
        RUN_NUMBER: ${{ github.run_number }}
        WORKFLOW: ${{ github.workflow }}
